### ISSUE TITLE
Internal error when running `fleek apply`

### ISSUE THREAD

**Issue by srxavi** [ublue-os/fleek#141]
**Describe the bug**
Unable to apply after initialization

**To Reproduce**
Execute `fleek init` and then `fleek apply`

**Expected behavior**
It should not give an internal error

**Environment**
 - OS: macOS 13.3.1
 - Shell: zsh
 - fleek version 0.8.3

**Additional context**
![image](https://user-images.githubusercontent.com/173510/231962716-0485608b-15ef-4ad4-9a64-3318511efa31.png)

**Comment by bketelsen** [comment]
I had this error too. Something changed upstream in home-manager. I have a fix inbound shortly.

**Comment by dvidbruhm** [comment]
I just installed fleek for the first time using :

```
curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install
nix profile install github:ublue-os/fleek/main
fleek init
```

And then when I use `fleek apply` I have the same error as described above. I am also using zsh, but when I switch to bash it works as expected:

```
# ~/.fleek.yml
shell: bash
```

System info and error: 
```
systems:
    - arch: x86_64
      hostname: desktop-nobara
      os: linux
      username: david
```
![image](https://user-images.githubusercontent.com/15694483/233445627-a1c30724-68b3-4b8d-967b-1d6abcbd7880.png)
