### ISSUE TITLE
A global fleek file

### ISSUE THREAD

**Issue by dnkmmr69420** [ublue-os/fleek#143]
**Is your feature request related to a problem? Please describe.**
A global fleek file in either `/etc/nix/global-fleek.yml` or `/etc/global-fleek.yml` or `/etc/fleek/global-fleek.yml`

**Describe the solution you'd like**
`global-fleek.yml` will be a very simple file that kind of looks like this

```
global-packages:
programname1
programname2
random-something
```

then in ~/.fleek.yml there will be a section for global packages

```
global-packages:
```

whenever you run `fleek apply` it will read `global-fleek.yml` and will make the global-packages section of the config `~/.fleek.yml` exactly the same as `global-fleek.yml`

to add or remove packages, you can just edit the config.

It will be good for setting default packages system wide

**Describe alternatives you've considered**
An alternative is to use nix profile to install things using root

**Comment by bketelsen** [comment]
can't be done with home-manager
