### ISSUE TITLE
How do I upgrade all my stuff?

### ISSUE THREAD

**Issue by bonds** [ublue-os/fleek#144]
**Is your feature request related to a problem? Please describe.**

I don't know how to upgrade Fleek. I don't know how to upgrade packages installed by Fleek.

**Describe the solution you'd like**

I'd like to run ``$ fleek upgrade`` and have it upgrade Fleek and upgrade all the packages Fleek manages.

**Describe alternatives you've considered**

This will update Fleek itself:

```
$ nix profile upgrade ".*"
```

This will update "iterm2", which is an app I installed using Fleek:

```
$ fleek remove iterm2 --apply
$ fleek add iterm2 --apply
```

I note that:

```
$ fleek update --apply
```

didn't seem to update iterm2 to the latest version, only removing it then adding it did. I guess I'm unclear what ``fleek update --apply`` is supposed to do...get the latest list of available apps but not upgrade anything that's already installed?

**Additional context**

none

**Comment by bonds** [comment]
Thanks! I tried to follow those new directions, but I blocked on this error:

```
$ nix run github:ublue-os/fleek -- apply
 [*]  Apply fleek configuration
 [i]  Enter User Details for Git Configuration:
Name Scott Bonds
Use detected email: scott@ggr.com Yes
  ERROR
  ERROR   Error: no choices provided
  ERROR
```

**Comment by bketelsen** [comment]
i'm speculating that you don't have an SSH key in ~/.ssh/ and fleek doesn't account for no keys existing.
Can you confirm that?
If you want to proceed until I can make a fix, generate an ssh key with these instructions:
https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent
then edit your ~/.fleek.yml file to add the key location in the users: array and run the `apply` command again.

**Comment by bonds** [comment]
> i'm speculating that you don't have an SSH key in ~/.ssh/ and fleek doesn't account for no keys existing.
> Can you confirm that?

Correct. I'm using [Secretive](https://github.com/maxgoedjen/secretive) as a hardware based SSH key, so I don't have a SSH key in ~/.ssh

> If you want to proceed until I can make a fix, generate an ssh key with these instructions:
> https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent
> then edit your ~/.fleek.yml file to add the key location in the users: array and run the `apply` command again.

I generated a key and then tried again. At first I got this error:

```
$ nix run github:ublue-os/fleek -- apply
 [*]  Apply fleek configuration
 [i]  Enter User Details for Git Configuration:
Name Scott Bonds
Use detected email: scott@ggr.com Yes
Choose Git SSH Key id_ed25519.pub
Error: runtime error: invalid memory address or nil pointer dereference
```

...but running ``nix run github:ublue-os/fleek -- apply`` again worked, including adding the user section to my fleek config.

**Comment by bketelsen** [comment]
That leads me to think that the `github:ublue-os/fleek` flake was cached at an older version locally. Strange indeed.

**Comment by bonds** [comment]
LGTM
