### ISSUE TITLE
home-manager switch does not work

### ISSUE THREAD

**Issue by yanns** [ublue-os/fleek#158]
**Describe the bug**
When I run:
```
home-manager switch
```
I got the following error:
```
/Users/yannsimon/.nix-profile/bin/home-manager: line 96: configFile: unbound variable
```

**Environment**
 - OS: macOS 13.3.1 (22E261)
 - Shell: zsh
 - fleek version: vv0.8.5

**Comment by yanns** [comment]
By looking at the source:
```
# Attempts to set the HOME_MANAGER_CONFIG global variable.
#
# If no configuration file can be found then this function will print
# an error message and exit with an error code.
function setConfigFile() {
    if [[ -v HOME_MANAGER_CONFIG ]] ; then
        if [[ -e "$HOME_MANAGER_CONFIG" ]] ; then
            HOME_MANAGER_CONFIG="$(realpath "$HOME_MANAGER_CONFIG")"
        else
            _i 'No configuration file found at %s' \
               "$HOME_MANAGER_CONFIG" >&2
            exit 1
        fi
    elif [[ ! -v HOME_MANAGER_CONFIG ]]; then
        local configHome="${XDG_CONFIG_HOME:-$HOME/.config}"
        local hmConfigHome="$configHome/home-manager"
        local nixpkgsConfigHome="$configHome/nixpkgs"
        local defaultConfFile="$hmConfigHome/home.nix"
        local configFlake

        if [[ -e "$defaultConfFile" ]]; then
            configFile="$defaultConfFile"
        elif [[ -e "$nixpkgsConfigHome/home.nix" ]]; then
            configFile="$nixpkgsConfigHome/home.nix"
            # translators: The first '%s' specifier will be replaced by either
            # 'home.nix' or 'flake.nix'.
            _iWarn $'Keeping your Home Manager %s in %s is deprecated,\nplease move it to %s' \
                   'home.nix' "$nixpkgsConfigHome" "$hmConfigHome" >&2
        elif [[ -e "$HOME/.nixpkgs/home.nix" ]]; then
            configFile="$HOME/.nixpkgs/home.nix"
            _iWarn $'Keeping your Home Manager %s in %s is deprecated,\nplease move it to %s' \
                   'home.nix' "$HOME/.nixpkgs" "$hmConfigHome" >&2
        fi

        if [[ $configFile ]]; then
            HOME_MANAGER_CONFIG="$(realpath "$configFile")"
        else
            _i 'No configuration file found. Please create one at %s' \
               "$defaultConfFile" >&2
            exit 1
        fi
    fi
}
```
the line 96 is `if [[ $configFile ]]; then`.
`$configFile` is being used without being initialized before?

**Comment by yanns** [comment]
The source: https://github.com/nix-community/home-manager/blob/master/home-manager/home-manager#L96

**Comment by yanns** [comment]
I've opened an [issue on home-manager](https://github.com/nix-community/home-manager/issues/3900)

**Comment by mcdent** [comment]
I just cane across this same issue. Quick question, how do you go back to managing with fleek after you did an eject?

**Comment by mcdent** [comment]
> I have not done any eject

sorry my bad, you did `switch` . 
Do you have any idea? Or is there a way to remove fleek and start again. 
I  installed it on a second host but realised I should have done a `fleek init git@github.com:username/fleek.git` to use my git repo. hmmmm.

**Comment by yanns** [comment]
I'm not sure what you're asking.
I'm very beginner.
I was using `topgrade` to update my systems, and it's failing when trying to upgrade the nix packages.

**Comment by yanns** [comment]
The issue is fixed now: https://github.com/nix-community/home-manager/issues/3900#issuecomment-1517561711
If someone knows how to update home manager?
Do we have to wait for a release?

**Comment by bketelsen** [comment]
you can run `fleek update` to get the new home-manager

**Comment by bketelsen** [comment]
please report back if that works @yanns

**Comment by yanns** [comment]
`fleek update` works, but `home-manager switch` still fails with the same issue.

**Comment by yanns** [comment]
After a `fleek apply`:
```
$ home-manager switch
No configuration file found. Please create one at /Users/yannsimon/.config/home-manager/home.nix
```

**Comment by yanns** [comment]
Maybe I should not use `home-manager switch` at all. I could configure `topgrade` not to take care of it.

**Comment by bketelsen** [comment]
yes, you want to let fleek do the upgrades, and not use `home-manager`. Fleek uses templates to apply your configurations from the fleek.yml file to your nix configs. without running fleek, it won't apply the changes.

**Comment by yanns** [comment]
ok thanks a lot!
