### ISSUE TITLE
fleek init --force (doesn't seem to work/exist)

### ISSUE THREAD

**Issue by mcdent** [ublue-os/fleek#159]
When running certain `init` command we may receive a message like
`source: cowardly refusing to overwrite config file without --force flag`
However the --force switch does not seem to exist, nor does it make any difference using the flag.

I assume when we use the flag with init, it should not warn us and should overwrite the config files?
Thanks

**Comment by bketelsen** [comment]
thanks for the report. I'll investigate.

**Comment by grahamc** [comment]
A few days ago I tried fleeks and hit a bug (https://github.com/ublue-os/fleek/issues/147#issuecomment-1514885045) I tried again today and came to this:

```
grahamc@scruffy:~/ > nix run github:ublue-os/fleek -- init
 [*]  Initialize fleek
 [i]  Writing configuration files
 [i]  Bling Level: default
 [i]  Enter User Details for Git Configuration:
Name Graham Christensen
Use detected email: graham@grahamc.com Yes
Choose Git SSH Key id_ed25519.pub
  ERROR   
  ERROR   
          Error: Creating configuration files
          source: cowardly refusing to overwrite config file without --force flag
  ERROR   
```

...so I tried again:

```
grahamc@scruffy:~/ > nix run github:ublue-os/fleek -- init --force
 [*]  Initialize fleek
 [i]  Writing configuration files
 [i]  Bling Level: default
 [i]  Enter User Details for Git Configuration:
Name Graham Christensen
Use detected email: graham@grahamc.com Yes
Choose Git SSH Key id_ed25519.pub
  ERROR   
  ERROR   
          Error: Creating configuration files
          source: cowardly refusing to overwrite config file without --force flag
  ERROR   
```

**Comment by bketelsen** [comment]
I'll take a look at the --force code in init and see where I've missed the flag. Thanks for the updated report!

**Comment by grahamc** [comment]
In the meantime, what should I delete to start fresh? :)

**Comment by bketelsen** [comment]
fixed by https://github.com/ublue-os/fleek/pull/173

**Comment by bketelsen** [comment]
> In the meantime, what should I delete to start fresh? :)

~/.fleek.yml
and 
~/.local/share/fleek
