### ISSUE TITLE
Init with git is broken

### ISSUE THREAD

**Issue by lamarios** [ublue-os/fleek#170]
**Describe the bug**
using fleek init with a github repo is broken

**To Reproduce**
```
fleek init git@github.com:lamarios/fleek.git
  ERROR   
  ERROR   Error: unknown command "git@github.com:lamarios/fleek.git" for "fleek init"
  ERROR   
```

**Expected behavior**
fleek to initialize properly

**Environment**
 - OS:  fedora silverblue
 - Shell: zsh
 - fleek version: 0.9.0

**Comment by bketelsen** [comment]
Please try `fleek join git@github....` instead. I'm doing a release today and the docs are behind the app by a few hours.

**Comment by lamarios** [comment]
it worked well, thanks !

**Comment by bketelsen** [comment]
Thanks for letting me know!
