### ISSUE TITLE
doc: improve how to add a computer

### ISSUE THREAD

**Issue by yanns** [ublue-os/fleek#175]
On https://getfleek.dev/docs/multiple#add-a-new-computer

We could understand that the first step is `fleek init`. But if we do so, the `join` command will fail as files are already existing.

The first step should be:
```
nix run github:ublue-os/fleek -- join
```

Then the second step for fleek apply should be
```
nix run github:ublue-os/fleek -- apply
```
(and not `join` again)

If we want, I can make a PR for the docs (I could not find the repo)

**Comment by bketelsen** [comment]
yes please!  https://github.com/bketelsen/getfleek.dev is the repo

**Comment by bketelsen** [comment]
done.

**Comment by yanns** [comment]
Cool thanks.
I've also opened https://github.com/bketelsen/getfleek.dev/pull/3
