### ISSUE TITLE
Not sure how to add package with same name

### ISSUE THREAD

**Issue by jahanson** [ublue-os/fleek#183]
I'm trying to add the `helm` package but soon realize that there are more than one. How do I specify which one to install and apply?

![image](https://user-images.githubusercontent.com/1548511/234883619-d0e8185e-3d33-4338-ab78-e0c821875097.png)

**Comment by bketelsen** [comment]
you're experiencing a bug in the search that didn't display the correct package name. it was fixed in the 0.9.0 release. Here's the same search on the current release:

```
❯ fleek search helm
 [*]  Search the package repository
 [✓]  Reading package cache                                                     
 [i]  Exact Matches
Package                 | Version | Description
kubernetes-helm-wrapped | 3.11.3  | A package manager for kubernetes
helm                    | 0.9.0   | A free, cross-platform, polyphonic synthesizer

 [i]  Try `fleek add kubernetes-helm-wrapped` to install kubernetes-helm-wrapped
 [i]  Try `fleek add helm` to install helm
 [✓]  Operation completed successfully

```
Here are upgrade instructions: https://getfleek.dev/docs/upgrade

**Comment by bketelsen** [comment]
reference: https://github.com/ublue-os/fleek/issues/164

**Comment by jahanson** [comment]
Oh, yeah. I guess was running an older version. It was still using a default nix profile for fleek. After removing that the upgrade went smoothly and I can see unique package names in there now.

Thank you!

**Comment by bketelsen** [comment]
thanks for reporting success, I appreciate it.
