### ISSUE TITLE
source a file at login

### ISSUE THREAD

**Issue by jahanson** [ublue-os/fleek#186]
Usually I'd append to .bashrc or .profile but I can't access those as they're read only. What is the fleek/nix way of doing this?

**Comment by jahanson** [comment]
Is there no equivalent in fleek? I'm just trying to work based off what i'm used to. If there is an equivalent or workaround I haven't been able to find it in the docs.

**Comment by EinoHR** [comment]
AFAIK there's nothing in fleek but nix+home-manager might.

**Comment by bketelsen** [comment]
in your user.nix file you can add an `initExtra` list to your bash/zsh configuration.  See home manager docs (https://nix-community.github.io/home-manager/options.html#opt-programs.bash.initExtra) for details.

**Comment by jahanson** [comment]
Am I correct in assuming I need to edit `~/.nix-profile/manifest.nix` ?

**Comment by bketelsen** [comment]
no, you'll want to edit your user.nix file in the fleek configuration directory, which is probably `~/.local/share/fleek`

**Comment by jahanson** [comment]
Awesome! Appreciate this. This worked great for my use case.
