### ISSUE TITLE
Install is f@#kd up. 

### ISSUE THREAD

**Issue by SoSoWow** [ublue-os/fleek#194]
Could not find suitable profile directory, tried /var/home/muchhustle-/.local/state/home-manager/profiles and /nix/var/nix/profiles/per-user/muchhustle-
  ERROR   
  ERROR   Error: exit status 1
  ERROR   
  ERROR   
  ERROR   Error: 
  ERROR   
  ERROR   There was an internal error. Run with FLEEK_DEBUG=1 for a detailed error message, and consider reporting it at https://github.com/ublue-os/fleek/issues

Fedora Kinoite
Konsole/Bash
yada yada

**Comment by nullfrctl** [comment]
Yup, I have exactly this.
I'm on uBlue Silverblue btw.

**Comment by stationaryStation** [comment]
Same on uBlue BlueFin

**Comment by bketelsen** [comment]
Workaround: run `nix profile list` - or any other `nix profile` command which will force the creation of the profile dir. Then you can continue with fleek. I am still trying to track down which installers have this problem

**Comment by nullfrctl** [comment]
That worked.

**Comment by bketelsen** [comment]
fixed by #214
