### ISSUE TITLE
allow git to be not managed by fleek 

### ISSUE THREAD

**Issue by 1024bees** [ublue-os/fleek#200]
**Is your feature request related to a problem? Please describe.**
Currently git 2.40 has some buggy behaviour that emerges with rust, see https://github.com/arxanas/git-branchless/issues/894 and https://github.com/libgit2/libgit2/issues/6531

**Describe the solution you'd like**
Allowing git to be not managed by fleek -- this is a bit of a toe stubber and being able to have a system git used would be nice

**Describe alternatives you've considered**
Having git version be able to be tightly controlled by fleek e.g, being able to rollback to git 2.39.2 would work,  however this doesn't seem to be a natural use case of nix

**Comment by bketelsen** [comment]
This one is tricky, because fleek's configuration has a lot of dependencies on git. If we remove git from the install, we will have to remove all the git configuration from the generated flake as well.

**Comment by 1024bees** [comment]
Yeah, that makes sense. Would you be open to creating an interface to pin a version of git specifically? I'd be open to attempt create an MR for whatever interface you'd prefer for managing package version / git version / etc. 


Also understandable if you'd just like to punt on it -- it does make rust development frustrating but I have work around on my end (temporarily renaming the .git folder).

**Comment by bketelsen** [comment]
If you were using home-manager directly how would you accomplish this?
