### ISSUE TITLE
Hey, what's up with the project? 😊

### ISSUE THREAD

**Issue by ZeroDeth** [ublue-os/fleek#207]
**Is your feature request related to a problem? Please describe.**

Hey there [@Maintainers],

First off, high five for all the work you've done on this project so far! 👏 Seriously, it's been super useful to a bunch of us, and we just want to give a huge shout-out to you for all the amazing stuff you've done here.

Lately, though, we've been noticing a bunch of new issues popping up, and it's looking a little quiet on your end. We totally get that maintaining a project like this is no small task (you're basically superheroes in our book for getting it this far! 🦸‍♀️🦸‍♂️).

So, we're just reaching out to get a feel for what's going on. Are you guys planning to keep on keeping on with this project? Any cool new updates or plans on the horizon that you could share?

And if you're stepping back for a bit, no worries at all. But could you let us know? If that's the case, we might start looking at what we can do from our end - whether that's finding alternatives, or even considering a fork to keep things moving.

Thanks a ton for everything you've done so far. Looking forward to hearing from you soon!

Best,

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bketelsen** [comment]
I'm alive. Just finished the devbox [integration](https://www.jetpack.io/devbox/docs/devbox_global/#using-fleek-with-devbox-global) to give people more options if they don't want their entire home managed.
