### ISSUE TITLE
Fleek on Wolfi (container): fleek init issue

### ISSUE THREAD

**Issue by nunix** [ublue-os/fleek#209]
**Describe the bug**
Trying to install Fleek on a container with Wolfi image (cgr.dev/chainguard/wolfi-base). No multi-user available, only root.
While doing the first `fleek init`, the command ends with the following error:
```bash
error: files '/nix/store/zdf22bp791y42cil8aab085ssnixplnz-home-manager-path/share/fish/vendor_completions.d/fleek.fish' and '/nix/store/r5jngwmksnr7bi9pp3g1flz5s8p9rhc0-fleek-v0.9.3/share/fish/vendor_completions.d/fleek.fish' have the same priority 5; use 'nix-env --set-flag priority NUMBER INSTALLED_PKGNAME' or type 'nix profile install --help' if using 'nix profile' to find out how to change the priority of one of the conflicting packages (0 being the highest priority)
```

This occurs for the files `fleek`, `fleek.fish`, `fleek.bash`. The error is always the same, stating there's a "duplicate" of packages.

**To Reproduce**
Here's the Dockerfile I created: https://github.com/nunix/boxwolfi/blob/main/Dockerfile
I follow the steps in there, and when I do the `fleek apply` I have the error above.

**Expected behavior**
The `fleek apply` command should apply a profile which shouldn't contain duplicates (at least that's how I understand it).

**Environment**
 - OS: WolfiOS container
 - Shell: bash
 - fleek version: 0.9.3

**Additional context**
The whole setup is being done in a container only.

**Comment by bketelsen** [comment]
The problem is using `nix profile install` for fleek. After you run fleek it tries to install itself in the home-manager profile which causes a conflict. remove the profile install and change your run commands to run fleek from the flake like these:
`nix run github:ublue-os/fleek -- init`

**Comment by nunix** [comment]
Really sorry for the delay @bketelsen and I just did it again, and worked fine. Thanks a lot!
