### ISSUE TITLE
join gives error: no such file or directory

### ISSUE THREAD

**Issue by dhassault** [ublue-os/fleek#228]
**Describe the bug**

When running the command to join I get this error message:
```
❯ nix run github:ublue-os/fleek -- join git@github.com:dhassault/fleek-config.git
 [*]  Join current computer to existing fleek configuration
Cloning into '/tmp/fleek844785243'...
remote: Enumerating objects: 124, done.
remote: Counting objects: 100% (124/124), done.
remote: Compressing objects: 100% (84/84), done.
remote: Total 124 (delta 94), reused 68 (delta 38), pack-reused 0
Receiving objects: 100% (124/124), 18.52 KiB | 824.00 KiB/s, done.
Resolving deltas: 100% (94/94), done.
  ERROR   
  ERROR   Error: open /var/home/dhassault/tmp/fleek844785243/.fleek.yml: no such file or directory
  ERROR   

```

**Environment**
 - OS: bluefin-dx-nvidia
 - Shell: bash
 - fleek version: 0.9.14

**Comment by tulilirockz** [comment]
Hello @bketelsen - This bug happens because of [this specific line](https://github.com/ublue-os/fleek/blob/main/internal/fleek/config.go#L416) in internal/fleek/config.go. It appends the home directory to the location if the location does not have it as a prefix, it makes sense for most use-cases of that function, but it breaks proper functionality in cases like this. I'll be sending you a pull request to remove that from the code - Although it might break something, so we should test it out

**Comment by bketelsen** [comment]
i think 0.9.15 will fix this. will test when the release is done

**Comment by bketelsen** [comment]
let me know if this still fails after updating, I'll reopen.

**Comment by tompscanlan** [comment]
I think I'm seeing the same thing after this change.  Looks like something interpreting a var with ~ or $HOME referenced where it shouldn't be.

```

~/tmp on ☁️  (us-east-1)
❯ HOME=/home/tscanlan fleek join git@github.com:tompscanlan/fleeking.git
 [*]  Join current computer to existing fleek configuration
Cloning into '/tmp/fleek2845969728'...
remote: Enumerating objects: 243, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 243 (delta 16), reused 10 (delta 6), pack-reused 223
Receiving objects: 100% (243/243), 49.23 KiB | 1.49 MiB/s, done.
Resolving deltas: 100% (205/205), done.
  ERROR
  ERROR   Error: open /home/tscanlan/tmp/fleek2845969728/.fleek.yml: no such file or directory
  ERROR

~/tmp on ☁️  (us-east-1)
❯ fleek version
0.9.17

```
