### ISSUE TITLE
After installing fleek the fleek command is not available

### ISSUE THREAD

**Issue by Alxhr0** [ublue-os/fleek#229]
**Describe the bug**
After installing fleek, the only way to interact with it through nix run because the fleek command itself is unavailable

**To Reproduce**
 - Install fleek
 - Apply configuration

**Expected behavior**
Users should be able to just type ``fleek apply`` rather than having to use ``nix run github:ublue-os/fleek -- apply``

**Environment**
 - OS: uBlue Kinoite
 - Shell: bash
 - fleek version: 0.9.14

**Comment by e-minguez** [comment]
```
nix profile install github:ublue-os/fleek
```

That did the trick for me. Not sure if it broke something else, I'm new to nix :D

**Comment by bketelsen** [comment]
the `nix profile install` works fine. There is a new installer being released today that should fix these issues.

**Comment by bketelsen** [comment]
the new installation instructions are in the README and on getfleek.dev
thanks for reporting!
