### ISSUE TITLE
[RFE] allowBroken via fleek configuration

### ISSUE THREAD

**Issue by e-minguez** [ublue-os/fleek#235]
**Is your feature request related to a problem? Please describe.**
There is an `allowBroken` nixpkgs setting that I would like to use but I'm not able to.

**Describe the solution you'd like**
Just like the 'unfree: true' setting, a "broken: true" setting would be nice

**Describe alternatives you've considered**
I've been trying to add the allowBroken setting everywhere but it doesn't work for me

**Additional context**
https://github.com/ublue-os/fleek/blob/main/internal/flake/templates/home.nix.tmpl#L8

**Comment by bketelsen** [comment]
Added this feature in #242
