### ISSUE TITLE
Adding `news.display` to user.nix breaks homeManager config on all new `fleek join`

### ISSUE THREAD

**Issue by mtalexan** [ublue-os/fleek#252]
**Describe the bug**

If the `news.display` option is set to anything in the `user.nix` when `fleek join` is run to enable the fleek config on a new machine, the homeManager activation fails with an error:

```
error: flake 'git+file:///home/MYUSER/.local/share/fleek' does not provide attribute 'packages.x86_64-linux.homeConfigurations."MYUSER@MYMACHINE".config.news.json.output', 'legacyPackages.x86_64-linux.homeConfigurations."MYUSER@MYMACHINE".config.news.json.output' or 'homeConfigurations."MYUSER@MYMACHINE".config.news.json.output'
```

No changes to the user.nix can fix this, it always errors out.

**To Reproduce**

1. Add to user.nix:
```
news.display = "notify";
```

2. `fleek apply` (this succeeds on existing systems)
3. On a new machine, `fleek join git@github.com:....`

**Expected behavior**
The `fleek join` succeeds.

**Environment**
 - OS: Ubuntu 22.04
 - Shell: bash
 - fleek version 0.9.18

**Additional context**

The bug seems to be a bootstrapping issue. HomeManager doesn't seem to include the generated JSON blob from `home-manager/misc/news.nix` for some reason when `fleek` installs it (maybe it's not just fleek related?), so the `activationPackage` errors out looking for the file during the `nix build` that occurs prior to applying the new home-manager generation.  Once it gets into this state, no new generations can be built or activated.

----

I was able to fix it by going to the `~/.local/share/fleek` directory, doing a direct `nix flake update` that bumped nixpkgs and home-manager to 23.11, and manually running `nix build .#homeConfigurations."MYUSER@MYMACHINE".activationPackage`. That successfully built, and I was then able to run `fleek apply` normally to get it to handle the git committing and pushing as well as regenerating.

---
Possibly related: The `home-manager news` command doesn't work with `home-manager news --flake .` until the 23.11 release.

**Comment by MikMik1011** [comment]
+1, it also broke for me, however i didn't even change news.display, it just broke.

managed to fix it the same way you did tho.

**Comment by mtalexan** [comment]
Since the default install of HomeManager is past the 23.11 where flake support was fixed, I'm going to close this.

It might be good to mention in the documentation how to view the news though since it notified on every fleek update. Specifically the `fleeks && home-manager news --flake .` command.  The direct `home-manager news` command, which theoretically would auto-detect if flakes were used, looks in the default home-manager installation location, which fleek doens't use.
