### ISSUE TITLE
`fleek add` causes `fleek apply` to fail

### ISSUE THREAD

**Issue by mtalexan** [ublue-os/fleek#253]
**Describe the bug**
In fleek 0.9.18 when `git.{autocommit,autopush}=true`, `fleek add` is now generating changes from the `.fleek.yml` then committing and pushing them.  This conflicts with `fleek  apply` that will error out if there is nothing to commit.

**To Reproduce**
1. `fleek add {anything}`
2. (notice it does the generate, git commit, and git push)
3. `fleek apply`
4. See error from `git commit`

**Expected behavior**
`fleek add {something} && fleek apply` should succeed to add the package and then activate the change.

**Environment**
 - OS: Ubuntu 22.04
 - Shell: bash or zsh (tested in both)
 - fleek version 0.9.18

**Additional context**

This appears to be new in fleek 0.9.18, I didn't experience this problem before I did up update of fleek.

**Comment by mtalexan** [comment]
Temporary workaround:

When the `fleek apply` fails with a `git commit` error after running however many `fleek add` and/or `fleek remove` commands, do the following:
1. `cd ~/.local/share/fleek/` (or use the alias `fleeks`)
2. `nix build ".#homeConfigurations.$(id -un)@$(hostname).activationPackage"
3. `home-manager switch --flake .`

This effectively runs what fleek would normally do after the commit, but does so manually.

**Comment by bketelsen** [comment]
I think it's missing a dirty check before it does the git add/commit/push cycle.

**Comment by mtalexan** [comment]
I used the version of fleek sometime before this, and `fleek add` didn't used to do anything with the git repo (from what I could tell). The issue is that now both `fleek add` and `fleek apply` try to do the commit and sync, but `fleek add` does only the git portion without the nix portion, and `fleek apply` does either/both only if the git workdir is still dirty.

**Comment by bketelsen** [comment]
@mtalexan can you replicate this with a `git status` in between the `add` and `apply`. I can't replicate this, and i'm not sure why.  Debug logs with `FLEEK_DEBUG=1 fleek <command>` would be useful too.

**Comment by mtalexan** [comment]
I never got back to this to replicate it again, but it seemed like it was probably just in the one exact version.  I'm on 0.10.5 and have no such issue anymore, and didn't have the issue when I was using the version prior to 0.9.18.

I'm pretty sure the problem was just an error checking vs responsibility one in the sub-commands for that specific release version.  The `fleek apply` didn't expect any other subcommand to do the push, so it was using that to determine if there was any nix installations to do.  But in the meantime the `fleek add` command had added support for committing and pushing.

Regardless, it's working without issue now.

**Comment by bketelsen** [comment]
thanks for reporting
