### ISSUE TITLE
`fleek apply` fails when bling is high because exa is deprecated

### ISSUE THREAD

**Issue by mkjeller** [ublue-os/fleek#271]
**Describe the bug**
Due to the `exa` package being deprecated `fleek apply` fails if bling is set to "high" because nix will not allow the user to install deprecated packages by default.

**To Reproduce**
1) Set `bling: high` in `.fleek.yml`
2) `fleek apply`

**Expected behavior**
All settings in .fleek.yml are applied and user is returned to an updated prompt with `ls` aliased to `exa`.

**Actual Behavior**
```
error:
       … while calling the 'derivationStrict' builtin

         at /builtin/derivation.nix:9:12: (source not available)

       … while evaluating derivation 'home-manager-generation'
         whose name attribute is located at /nix/store/9incrwprw2s90minyy0gpmwbxmrkcx1v-source/pkgs/stdenv/generic/make-derivation.nix:300:7

       … while evaluating attribute 'buildCommand' of derivation 'home-manager-generation'

         at /nix/store/9incrwprw2s90minyy0gpmwbxmrkcx1v-source/pkgs/build-support/trivial-builders/default.nix:87:14:

           86|       enableParallelBuilding = true;
           87|       inherit buildCommand name;
             |              ^
           88|       passAsFile = [ "buildCommand" ]

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: 'exa' has been removed because it is unmaintained upstream. Consider using 'eza', a maintained fork
  ERROR   
  ERROR   Error: exit status 1
  ERROR   
  ERROR   
  ERROR   Error: 
  ERROR   
  ERROR   There was an internal error. Run with FLEEK_DEBUG=1 for a detailed error message, and consider reporting it at https://github.com/ublue-os/fleek/issues
```

**Environment**
 - OS: Linux Mint 21.2
 - Shell: zsh
 - fleek version: 0.9.21

**Additional context**
Adding `exa` to the blocklist bypasses this.
Can manually add `eza` (the new fork) to the packages list, however this does not automatically configure `eza` as a replacement for `ls` the same way the `exa` managed package is.

**Comment by bketelsen** [comment]
thanks, fixed by #273
