### ISSUE TITLE
Add Packagekit Support

### ISSUE THREAD

**Issue by Champe20** [ublue-os/fleek#277]
While I love having a wrapper for nix, it would be so much better if it supported packagekit to install applications graphically.

**Comment by bketelsen** [comment]
fleek is cross platform, but PackageKit isn't.

 Feel free to take the ideas and config and run with a PackageKit implementation if that works for you.

**Comment by Champe20** [comment]
@bketelsen Where may I find an implementation of PackageKit and fleek.
