### ISSUE TITLE
Nix failed to install your new Home Manager profile

### ISSUE THREAD

**Issue by yanns** [ublue-os/fleek#288]
**Describe the bug**
` apply` fails with `Nix failed to install your new Home Manager profile`

**To Reproduce**
From https://github.com/ublue-os/fleek/issues/286#issuecomment-1729628411

**Expected behavior**
The apply should not fail

**Environment**
- OS: macOS Ventura
- Shell: zsh
- fleek version: 0.9.23

**Comment by bketelsen** [comment]
as noted in the linked issue, follow the directions given in the error message to resolve:
```
Perhaps there is a conflict with a package that was installed using
"nix profile install"? Try running

    nix profile list

and if there is a conflicting package you can remove it with

    nix profile remove {number | store path}```

I'll look at ways of predicting this problem and proactively fixing it.

**Comment by yanns** [comment]
Yes I confirm it's working.
