### ISSUE TITLE
bling `high` installs `yq` instead of `yq-go`

### ISSUE THREAD

**Issue by wrdls** [ublue-os/fleek#300]
**Describe the bug**

`yq` installs https://github.com/kislyuk/yq

To install https://mikefarah.gitbook.io/yq/ you want [yq-go](https://search.nixos.org/packages?channel=unstable&show=yq-go&from=0&size=50&sort=relevance&type=packages&query=yq-go)

**To Reproduce**

Configure bling level `high`

**Additional context**

This is especially annoying since packages installed through bling can't be uninstalled with `fleek remove yq`, but running `fleek add yq-go` will (correctly) throw a collision error:

```
error: collision between `/nix/store/ipmlbz96p88pss2dl4fnhn447mv59f3x-python3.10-yq-3.2.3/bin/yq' and `/nix/store/yil0c982v90wx88kv63fmsqz99hw786i-yq-go-4.35.1/bin/yq'
```

**Comment by bketelsen** [comment]
fixed in release 0.10.4
