### ISSUE TITLE
Open source the homepage

### ISSUE THREAD

**Issue by ShalokShalom** [ublue-os/fleek#315]
I wanted to contribute to the homepage, and don't find its source code.

**Comment by p5** [comment]
I believe the homepage is hosted under @bketelsen 's GitHub profile
https://github.com/bketelsen/getfleek.dev

**Comment by ShalokShalom** [comment]
It might be worth mentioning this somewhere. The "Github" icon on the webpage/doc page links to this repo. Thanks
